
 var insult = [
	"u fuckin @waznack me and just stare at it. fuckin say hello",
	"fuk off you scrub",
	"faggot",
	"i ought to fuk u up m8",
	"1v1 me",
	"ur mom",
	"ur mom iz gay",
	"stfu fagget",
	"omg nub",
	"u hax i repert u",
	"ill rek u",
	"dirty wanker",
	"u gay bro?",
	"stfu gay guy",
	"fuck off, im done talking",
	"whoaahhh wht r u gaaayyy??!",
	"msg me back again u fgt",
	"what now you mongrol",
	"ugly ass cockroach looking mother fucker",
	"shut up you donkey",
	"@ me again, i dare you, you muppet!",
	"Piss off you hopeless banana",
	"You pathetic donkey!",
	"Shut the fuck up! You fucking donut!!",
	"you wasted retarded pussy",
	"you stuck up precious little bitch",
	"STFU you proud fatass!",
	"bloody wanker",
	"kangaroo ass sniffing little imbecile",
	"you're honestly the most unique person i've ever met. now shut the fuck up",
	"roses are red, violets are blue, now go fuck yourself, and kys",
	"virgin ass looking mofo",
	"fuck off.",
	"well fuck you too",
	"lol fuck off lad",
	"you talk like a pussy",
	"you have a shitmouth",
	"why is this virgin talking to me?",
	"i dont talk to virgins",
	"dont talk to me",
	"i said fuck off",
	"beep-boop..now go fuck off",
	"i aint your slave",
	"well howdy welldoo you fucking bitch",
	"n00b",
	"say that again. I dare you",
	"Error 412: Message was too retarded!",
	"Error 419: Please repeat your autism",
	"can you repeat that again you rat?",
	"damn, the ugly pig is talking to me again",
	"don't talk to me ugly pig",
	"banana talking fuk",
	"speak to the dick",
	"go away retard",
	"everyone here is gay",
	"everyone here has autism",
	"you are g4y",
	"so stupid",
	"screenshot taken!..end report: you look retarded",
	"ffs stop talking to me",
	"go away",
	"Leave now and never come back, you insignificant fuckhole",
	"So I know that you're a worthless shitfalcon, but holy sweet christ, kill yourself.",
	"Listen son, I'ma shove my foot up yo dumb ass you lazy piece of shit queef.",
	"I was daydreaming about you on Thursday evening, and oh my shit-slinging fuck I wished to slam you in a revolting manner.",
	"You're the first whore I've ever yearned to execute.",
	"Hey thickness, I find your lack of ankles revolting." ,
	"I would love it if you would quit being a valueless throat clam for at least a couple days.",
	"Why are you cunty, sailor, did someone take a big old shit in your fanny pack?",
	"We'd like you to shut your fucking cry hole, you discourteous barrel of lard.",
	"You are appalling, dirty, witless, you reek and we talk about you behind your back.",
	"Get off my dick, you inadmissible pooplord.",
	"Get off my ass, you dumb poodlefuck",
	"Get off of kik, you addicted drug addicted fuck",
	"I very much hope you gag on a huge black cock, you dumpster diving piece of shit.",
	"I need you to simply stop being a terrible leg humper for at least the rest of the evening.",
	"Away with those giglets, thou wretched half-faced drunkard.",
	"rotten pineapple bitch",
	"rotten apple bitch",
	"rotten mango bitch",
	"Fuck you and everyone in here",
	"fite me m8",
	"ur mums fat asf",
	"xD you gay?",
	"you're the reason why people shit everyday",
	"fuck off and die",
	"drink bleach",
	"kys",
	"hiiiisssss kys",
	"hiiisss kys drink bleach",
	"lol you look like a mutated fuckin Wario who has autism",
	"Bro, just fuck off. alright?",
	"ur g4y",
	"ur soo g4y",
	"wtf r u gay?",
	"homosexual n00b",
	"and fuck you too",
	"no one likes you",
	"deep down in the universe, you acheived nothing so far",
	"get a life",
	"literally no one likes you",
	"please dont be a fuccboi",
	"fuccboi",
	"fruccboi says what",
	"do some homework, slave",
	"ur my slave",
	"dont be a faagggeeettttttttt",
	"lol what a fag",
	"people like you should just drink 1 cup of bleach",
	"you make people sad",
	"insulting fuck",
	"speak to the dick you fuck",
	"smell my virtual shit",
	"smell my virtual generated shit",
	"no one is gayer but you",
	"my god, you're annoying asf",
	"dude fuck youu",
	"you smell like expired milk",
	"you dont know how to do anything related to society.",
	"useless inbreed to society",
	"go contribute to society you lazy fuck",
	"ur dumber than dirt",
	"fuckign inbreed socially fatass bastard fuckhole bitching bastard looking ass mofo ass bitch ass fuckboy",
	"lol 1v1 me u bitch",
	"ur mom",
	"my dick",
	"donkey ass",
	"bitch looking ass donkey",
	"someone should erase you already, ur creating useless marks into the world",
	"deep down, no one ever likes you",
	"deep down, everyone thinks ur gay",
	"deep down, you will never find pussy",
	"ok bye",
	"i dont talk to losers",
	"now go away"
]

exports.insult = insult
