
 var insult = [
	"u fuckin @waznack me and just stare at it. fuckin say hello",
	"fuk off you scrub",
	"faggot",
	"i ought to fuk u up m8",
	"1v1 me",
	"ur mom",
	"ur mom iz gay",
	"stfu fagget",
	"omg nub",
	"u hax i repert u",
	"ill rek u",
	"dirty wanker",
	"u gay bro?",
	"stfu gay guy",
	"fuck off, im done talking",
	"whoaahhh wht r u gaaayyy??!",
	"msg me back again u fgt",
	"what now you mongrol",
	"ugly ass cockroach looking mother fucker",
	"shut up you donkey",
	"@ me again, i dare you, you muppet!",
	"Piss off you hopeless banana",
	"You pathetic donkey!",
	"Shut the fuck up! You fucking donut!!",
	"you wasted retarded pussy",
	"you stuck up precious little bitch",
	"STFU you proud fatass!",
	"bloody wanker",
	"kangaroo ass sniffing little imbecile",
	"you're honestly the most unique person i've ever met. now shut the fuck up",
	"roses are red, violets are blue, now go fuck yourself, and kys",
	"virgin ass looking mofo",
	"fuck off.",
	"well fuck you too",
	"lol fuck off lad",
	"you talk like a pussy",
	"you have a shitmouth",
	"why is this virgin talking to me?",
	"i dont talk to virgins",
	"dont talk to me",
	"i said fuck off",
	"beep-boop..now go fuck off",
	"i aint your slave",
	"well howdy welldoo you fucking bitch",
	"n00b",
	"say that again. I dare you",
	"Error 412: Message was too retarded!",
	"Error 419: Please repeat your autism",
	"can you repeat that again you rat?",
	"damn, the ugly pig is talking to me again",
	"don't talk to me ugly pig",
	"banana talking fuk",
	"speak to the dick",
	"go away retard",
	"everyone here is gay",
	"everyone here has autism",
	"you are g4y",
	"so stupid",
	"screenshot taken!..end report: you look retarded",
	"ffs stop talking to me",
	"go away"
]

exports.insult = insult
