
 var insult = [
	["fuk off you scrub", //hello,hallo,wattup, etc. (0)
	"i ought to fuk u up m8",
	"what now you mongrol",
	"shut up you donkey",
	"i dont talk to virgins",
	"dont talk to me",
	"well howdy welldoo you fucking bitch",
	"don't talk to me ugly pig",
	"go away",
	"i aint your slave,what do you expect a fucking answer?",
	"fuck off and die",
	"Bro, just fuck off. alright?",
	"literally no one likes you",
	"speak to the dick you fuck",
	"smell my virtual shit",
	"smell my virtual generated shit",
	"i dont talk to losers",
	"what now you mongrol"
	],
	[ //(1)
	"Leave now and never come back, you insignificant fuckhole", //goodbye 
	"fuck off and die",
	"ok bye"
	],
	[ //(2)
	"Listen son, I'ma shove my foot up yo dumb ass you lazy piece of shit queef.", //you
	"I would love it if you would quit being a valueless throat clam for at least a couple days.",
	"lol you look like a mutated fuckin Wario who has autism",
	"fucking inbreed socially fatass bastard fuckhole bitching bastard looking ass mofo ass bitch ass fuckboy",
	"you smell like expired milk",
	],
	[ //be nice (3)
	"I don't want to be kind to you, even your own family doesn't want to be kind to you, perhaps it would save everyone a lot of trouble if you just ended it."
	"shut the fuck up you sjw",
	"Wake the fuck up you fairy twat",
	"Fuck off you Pussy"
	],
	[ //(4)
	"deep down, you are a a dweeb", //deep down
	"deep down, you are nothing but a fucking worthless rat",
	"deep down, no one loves you, not even your fucking body",
	"deep down... holy shit! their's inches of fat I cant get through",
	"deep down , Fuck off already"
	],
	[
	"everyone here is gay", //everyone(5)
	"everyone here has autism",
	"Fuck you and everyone in here",
	"What a bunch of fuking panzees",
	],
	["fuck off.",
	"1v1 me",
	"faggot",
	"ur mom",
	"ur mom iz gay",
	"stfu fagget",
	"u hax i repert u",
	"ill rek u",
	"dirty wanker",
	"u gay bro?",
	"stfu gay guy",
	"fuck off, im done talking",
	"whoaahhh wht r u gaaayyy??!",
	"msg me back again u fgt",
	"ugly ass cockroach looking mother fucker",
	"@ me again, i dare you, you muppet!",
	"Piss off you hopeless banana",
	"You pathetic donkey!",
	"Shut the fuck up! You fucking donut!!",
	"you wasted retarded pussy",
	"you stuck up precious little bitch",
	"STFU you proud fatass!",
	"bloody wanker",
	"kangaroo ass sniffing little imbecile",
	"you're honestly the most unique person i've ever met. now shut the fuck up",
	"roses are red, violets are blue, I thought Voldemort, but then I saw you",
	"virgin ass looking mofo",
	"well fuck you too",
	"lol fuck off lad",
	"you talk like a pussy",
	"you have a shitmouth",
	"why is this virgin talking to me?",
	"i said fuck off",
	"beep-boop..now go fuck off",
	"n00b",
	"say that again. I dare you",
	"Error 412: Message was too retarded!",
	"Error 419: Please repeat your autism",
	"can you repeat that again you rat?",
	"damn, the ugly pig is talking to me again",
	"banana talking fuk",
	"speak to the dick",
	"go away retard",
	"you are g4y",
	"so stupid",
	"screenshot taken!..end report: you look retarded",
	"ffs stop talking to me"
	"So I know that you're a worthless shitfalcon, but holy sweet christ, kill yourself.",
	"I was daydreaming about you on Thursday evening, and oh my shit-slinging fuck I wished to slam you in a revolting manner.",
	"You're the first whore I've ever yearned to execute.",
	"Hey thickness, I find your lack of ankles revolting." ,
	"I would love it if you would quit being a valueless throat clam for at least a couple days.",
	"Why are you cunty, sailor, did someone take a big old shit in your fanny pack?",
	"We'd like you to shut your fucking cry hole, you discourteous barrel of lard.",
	"You are appalling, dirty, witless, you reek and we talk about you behind your back.",
	"Get off my dick, you gay cunt",
	"Get off my ass, you dumb poodlefuck",
	"Get off of kik, you addicted drug addicted fuck",
	"I very much hope you gag on a huge black cock, you dumpster diving piece of shit.",
	"I need you to simply stop being a terrible leg humper for at least the rest of the evening.",
	"Away with those giglets, thou wretched half-faced drunkard.",
	"rotten pineapple bitch",
	"rotten apple bitch",
	"rotten mango bitch",
	"fite me m8",
	"ur mums fat asf",
	"xD you gay?",
	"you're the reason why people shit everyday",
	"drink bleach",
	"kys",
	"hiiiisssss kys",
	"hiiisss kys drink bleach",
	"Bro, just fuck off. alright?",
	"ur g4y",
	"ur soo g4y",
	"wtf r u gay?",
	"homosexual n00b",
	"and fuck you too",
	"no one likes you",
	"deep down in the universe, you acheived nothing so far",
	"get a life",
	"please dont be a fuccboi",
	"fuccboi",
	"fuccboi says what",
	"do some homework, slave",
	"ur my slave",
	"dont be a faagggeeettttttttt",
	"lol what a fag",
	"people like you should just drink 1 cup of bleach everyday of your life until you slowly fucking die into obscurity",
	"you make people sad",
	"insulting fuck",
	"speak to the dick you fuck",
	"smell my virtual shit",
	"smell my virtual generated shit",
	"no one is gayer but you",
	"my god, you're annoying asf",
	"dude fuck youu",
	"you smell like expired milk",
	"you dont know how to do anything related to society.",
	"useless inbreed to society",
	"go contribute to society you lazy fuck",
	"ur dumber than dirt",
	"lol 1v1 me u bitch",
	"ur mom",
	"my dick",
	"donkey ass",
	"bitch looking ass donkey",
	"someone should erase you already, ur creating useless marks into the world",
	"deep down, no one ever likes you",
	"deep down, everyone thinks ur gay",
	"deep down, you will never find pussy",
	"I can't wait until you get chlamydia.",
	"u fuckin @waznack me and just stare at it. fuckin say hello"] //big 6
]

exports.insult = insult
